service: lambda-go
provider:
  name: aws
  runtime: go1.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:*
      Resource: "arn:aws:s3:::*"
package:
 exclude:
   - ./**
 include:
   - ./bin/**
functions:
  list-memes-func:
    handler: bin/list-memes-func
    events:
      - http:
          path: /list
          method: get
  generate-file-func:
    handler: bin/generate-file-func
    events:
      - http:
          path: /generate
          method: get